## Numpy 

In [1]:
import numpy as np


#### creating a numpy array

In [3]:
myarray1=np.array((1,2,3,4,5))

In [5]:
myarray1

array([1, 2, 3, 4, 5])

In [7]:
myarray2=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=float)

In [8]:
myarray2

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [10]:
myarray3=np.array([[1,2,3],[6,7,8]],dtype=complex)

In [11]:
myarray3

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [6.+0.j, 7.+0.j, 8.+0.j]])

In [13]:
myarray4=np.array([[1,2,3],[6,7,8]],dtype=str)

In [14]:
myarray4

array([['1', '2', '3'],
       ['6', '7', '8']], dtype='<U1')

In [15]:
myarray5=np.array([[1,2,3],[6,7,8]],dtype=int)

In [16]:
myarray5

array([[1, 2, 3],
       [6, 7, 8]])

In [19]:
myarray6=np.array([[1,2,3],[6,7,8]],dtype=bool)

In [20]:
myarray6

array([[ True,  True,  True],
       [ True,  True,  True]])

#### array information

In [22]:
# array with element in the range  with matrix shape
myarray7=np.arange(0,9)

In [23]:
myarray7

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
myarray8=np.arange(0,9).reshape(3,3)

In [27]:
myarray8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
myarray8=np.arange(0,9).reshape(3,5)
# we should make the equal size of the array, as mention above
#ValueError: cannot reshape array of size 9 into shape (3,5)

ValueError: cannot reshape array of size 9 into shape (3,5)

In [32]:
myarray8.shape# it gives the shape of the array hai guys 

(3, 3)

In [34]:
myarray8.ndim# it gives the no. of the dimension of the array

2

In [36]:
myarray8.dtype # it gives the data type of the array

dtype('int32')

In [37]:
myarray8.dtype.name # it give name of the data type 

'int32'

In [39]:
myarray8.itemsize # it gives the size of the item

4

In [41]:
#create the numpy arry of all 0 
np.zeros((4,5)) # where 4 = row and 5 = columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
#create the numpy arry of all 1
np.ones((3,3)) # by defult it gives float

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
#create the numpy arry of all 1
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [47]:
#create the numpy arry of all 1
np.ones((3,3),dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [48]:
# numpy arra whose intial content is random and depends on the state of meomry
np.empty((3,4))

array([[1.09677995e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.04082753e-047, 5.24775169e-090,
        1.65609221e-047],
       [8.41452934e+164, 5.06173311e-038, 3.99910963e+252,
        4.93432906e+257]])

In [49]:
#create the numpy array of evenly spaced values (start,stop,step)
np.arange(20,50,6)

array([20, 26, 32, 38, 44])

In [53]:
#create evenly spaced samples 
#calculated ove the interval (start,stop)
np.linspace(5,7)

array([5.        , 5.04081633, 5.08163265, 5.12244898, 5.16326531,
       5.20408163, 5.24489796, 5.28571429, 5.32653061, 5.36734694,
       5.40816327, 5.44897959, 5.48979592, 5.53061224, 5.57142857,
       5.6122449 , 5.65306122, 5.69387755, 5.73469388, 5.7755102 ,
       5.81632653, 5.85714286, 5.89795918, 5.93877551, 5.97959184,
       6.02040816, 6.06122449, 6.10204082, 6.14285714, 6.18367347,
       6.2244898 , 6.26530612, 6.30612245, 6.34693878, 6.3877551 ,
       6.42857143, 6.46938776, 6.51020408, 6.55102041, 6.59183673,
       6.63265306, 6.67346939, 6.71428571, 6.75510204, 6.79591837,
       6.83673469, 6.87755102, 6.91836735, 6.95918367, 7.        ])

In [55]:
#return a new array of given shape and type 
# filled with fil value
np.full((3,5),10)
# where 3= no. rows,5=no.columns and 10= vlaues that need to print


array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [58]:
# create the array with digonal elment unity
# create the identity matrix
np.eye(1)
#it is unity matrix

array([[1.]])

In [59]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [60]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
#create the random floats in the 
# half-open interval
np.random.random((3,3))

array([[0.3271644 , 0.81304342, 0.64545387],
       [0.63476455, 0.46367393, 0.11254737],
       [0.68548926, 0.84610829, 0.49252457]])